# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_suggest', models.BigIntegerField(blank=True, null=True)),
                ('base_money', models.BigIntegerField(default=0)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.BigIntegerField(blank=True)),
                ('real_price', models.BigIntegerField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sort_version', models.IntegerField(blank=True, db_index=True, default=0)),
                ('sort_value', models.IntegerField(db_index=True, default=0)),
                ('read', models.BooleanField(default=False)),
                ('buyable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['read', '-sort_version', '-sort_value', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_charity', models.BooleanField(default=False)),
                ('image_url_0', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_count', models.SmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('n_likes', models.IntegerField(default=0, editable=False)),
                ('n_reposters', models.IntegerField(default=0, editable=False)),
                ('n_comments', models.IntegerField(default=0, editable=False)),
                ('disable_after_buy', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=False)),
                ('deliver_time', models.IntegerField(default=2)),
                ('confirmed_to_show', models.BooleanField(default=False)),
                ('waiting_to_confirm', models.BooleanField(default=True, editable=False)),
                ('remaining_qeroons', models.PositiveIntegerField(default=0)),
                ('total_invested_qeroons', models.PositiveIntegerField(default=0)),
                ('ads_included', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=14, null=True)),
                ('next_buy_ben', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_repost', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggests', to='posts.Post')),
            ],
        ),
    ]
