# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Like'),
        ),
    ]
