# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170811_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
