# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggests', to='posts.Post')),
                ('suggest_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggesteds', to=settings.AUTH_USER_MODEL)),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
