# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170816_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='base_money',
            field=models.BigIntegerField(default=0),
        ),
    ]
