# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirmed_to_show',
            field=models.BooleanField(default=False),
        ),
    ]
