# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='reposter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposters', to=settings.AUTH_USER_MODEL),
        ),
    ]
