# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('posts', '0005_post_waiting_to_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='n_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='n_reposters',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='waiting_to_confirm',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
