# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170818_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highest_suggester',
        ),
    ]
