# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_auction_highest_suggester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-sort_time']},
        ),
    ]
