# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
