# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-read', 'not_read_sort_value', '-sort_time']},
        ),
        migrations.AddField(
            model_name='feed',
            name='not_read_sort_value',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sort_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
