# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20170812_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='reposter',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='shared',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='n_likes',
            field=models.IntegerField(default=0),
        ),
    ]
