# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_delete_feedmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-read', '-not_read_sort_value', '-viewing_version', 'sort_time']},
        ),
        migrations.AddField(
            model_name='feed',
            name='viewing_version',
            field=models.IntegerField(default=1),
        ),
    ]
