# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_n_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-pk']},
        ),
    ]
