# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170903_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['read', '-not_read_sort_value', 'sort_time']},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='viewing_version',
        ),
    ]
