# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170815_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_after_buy',
            field=models.BooleanField(default=True),
        ),
    ]
