# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_delete_after_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='delete_after_buy',
            new_name='disable_after_buy',
        ),
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
