# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170815_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
