# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_feed_buyable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['read', '-sort_version', '-sort_value']},
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='not_read_sort_value',
            new_name='sort_value',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='sort_time',
        ),
        migrations.AddField(
            model_name='feed',
            name='sort_version',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
