# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170909_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='real_price',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_price',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='remaining_qeroons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
