# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170909_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ads_included',
            field=models.BooleanField(default=False),
        ),
    ]
