# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_feed_reposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deliver_time',
            field=models.IntegerField(default=24),
        ),
    ]
