# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_ads_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_invested_qeroons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
