# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20170911_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deliver_time',
            field=models.IntegerField(default=2),
        ),
    ]
