# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20170915_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
