# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next_buy_ben',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
