# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_next_buy_ben'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image_url_0',
        ),
        migrations.AddField(
            model_name='post',
            name='image_count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
