# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20170918_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['read', '-sort_version', '-sort_value', '-pk']},
        ),
    ]
