# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20170927_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='n_comments',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
