# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_profilepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepost',
            options={'ordering': ['-pk']},
        ),
    ]
