# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_profile_followings_+', to='profiles.Profile'),
        ),
    ]
