# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170811_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.BigIntegerField(null=True),
        ),
    ]
