# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
