# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_phonenumber_phonenumberconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberconfirmation',
            name='last_request_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
