# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170824_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
