# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170811_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
