# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='feeds',
        ),
    ]
