# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170826_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
