# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170812_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='n_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='n_followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
