# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_of_rates',
            field=models.IntegerField(default=0),
        ),
    ]
