# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_count_of_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_reposts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_successful_reposts',
            field=models.IntegerField(default=0),
        ),
    ]
