# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170903_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_visiting_app',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_successful_reposts',
            field=models.IntegerField(default=1),
        ),
    ]
