# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170903_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qeroon',
            field=models.IntegerField(default=100),
        ),
    ]
