# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_review_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='uuid',
        ),
    ]
