# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_review_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
