# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_review_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
