# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QeroonTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('suspended_qeroon', models.IntegerField()),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('got_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('re', 'pending'), ('ca', 'canceled'), ('go', 'got')], default='re', max_length=2)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qeroon_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pe', 'pending'), ('de', 'delivered'), ('ca', 'canceled')], default='pe', max_length=2)),
                ('suspended_money', models.BigIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('deliver_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('confirm_code', models.IntegerField(default=0)),
                ('rate_status', models.CharField(choices=[('nr', 'not rateable'), ('cr', 'can rate'), ('ra', 'rated')], default='nr', max_length=2)),
                ('auction_failed', models.BooleanField(default=False)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('deleted_by_buyer', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
                ('reposter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_transaction', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='profiles.Review')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
