# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pe', 'pending'), ('de', 'delivered'), ('ca', 'canceled')], default='pe', max_length=2)),
                ('confirmed', models.BooleanField(default=False)),
                ('suspended_money', models.BigIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confirm_time', models.DateTimeField(null=True)),
                ('deliver_time', models.DateTimeField(null=True)),
                ('cancel_time', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
            ],
        ),
    ]
