# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post'),
        ),
    ]
