# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_transaction_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='feed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reposter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_transaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
