# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='confirm_time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
    ]
