# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170909_1341'),
        ('transactions', '0005_auto_20170825_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='QeroonTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('suspended_qeroon', models.IntegerField()),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
                ('got_time', models.DateTimeField()),
                ('cancel_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('re', 'pending'), ('ca', 'canceled'), ('go', 'got')], default='re', max_length=2)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
