# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170909_1421'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='qeroontransaction',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirm_code',
            field=models.IntegerField(default=0),
        ),
    ]
