# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170909_1532'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='qeroontransaction',
            managers=[
            ],
        ),
    ]
