# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_review'),
        ('transactions', '0010_auto_20170910_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='allow_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Review'),
        ),
    ]
