# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20170911_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='allow_rate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate_status',
            field=models.CharField(choices=[('nr', 'not rateable'), ('cr', 'can rate'), ('ra', 'rated')], default='nr', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='profiles.Review'),
        ),
    ]
