# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20170911_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qeroontransaction',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['pk']},
        ),
    ]
