# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20170915_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_by_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deliver_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
