# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20171003_1359'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'inappropriate'), ('IN', 'insult'), ('SP', 'spam'), ('OT', 'other')], default='OT', max_length=2)),
                ('text', models.CharField(blank=True, max_length=400, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.Comment')),
            ],
        ),
    ]
