# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportcomment_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='delete_comment',
            field=models.BooleanField(default=False),
        ),
    ]
