# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20171014_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotification',
            name='who_did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_post_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
