# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170828_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnotification',
            name='status',
            field=models.CharField(choices=[('bu', 'buy'), ('SE', 'sell'), ('AU', 'auction'), ('DE', 'delivered'), ('AF', 'auction_failed')], max_length=2),
        ),
    ]
