# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_postnotification_who_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotification',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
